[package]
name = "tourboxneo-cli"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
crossbeam-channel = "0.5.5"
ctrlc = "3.2.2"
serialport = "4.2.0"
uinput = "0.1.3"